-- AlterTable
ALTER TABLE `admin` ADD COLUMN `updatedPasswordAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `instructor` ADD COLUMN `updatedPasswordAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `student` ADD COLUMN `updatedPasswordAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
